#include "MEMDataBase/MEMDataBase/interface/DataBaseMEMResult.h"

DataBaseMEMResult::DataBaseMEMResult(){
  p=-99;
  p_sig=-99;
  p_bkg=-99;
  p_AbsoluteStatUp=-99;
  p_AbsoluteStatDown=-99;
  p_AbsoluteStatUp=-99;
  p_AbsoluteStatDown=-99;
  p_AbsoluteScaleUp=-99;
  p_AbsoluteScaleDown=-99;
  p_AbsoluteFlavMapUp=-99;
  p_AbsoluteFlavMapDown=-99;
  p_AbsoluteMPFBiasUp=-99;
  p_AbsoluteMPFBiasDown=-99;
  p_FragmentationUp=-99;
  p_FragmentationDown=-99;
  p_SinglePionECALUp=-99;
  p_SinglePionECALDown=-99;
  p_SinglePionHCALUp=-99;
  p_SinglePionHCALDown=-99;
  p_FlavorQCDUp=-99;
  p_FlavorQCDDown=-99;
  p_TimePtEtaUp=-99;
  p_TimePtEtaDown=-99;
  p_RelativeJEREC1Up=-99;
  p_RelativeJEREC1Down=-99;
  p_RelativeJEREC2Up=-99;
  p_RelativeJEREC2Down=-99;
  p_RelativeJERHFUp=-99;
  p_RelativeJERHFDown=-99;
  p_RelativePtBBUp=-99;
  p_RelativePtBBDown=-99;
  p_RelativePtEC1Up=-99;
  p_RelativePtEC1Down=-99;
  p_RelativePtEC2Up=-99;
  p_RelativePtEC2Down=-99;
  p_RelativePtHFUp=-99;
  p_RelativePtHFDown=-99;
  p_RelativeFSRUp=-99;
  p_RelativeFSRDown=-99;
  p_RelativeStatFSRUp=-99;
  p_RelativeStatFSRDown=-99;
  p_RelativeStatECUp=-99;
  p_RelativeStatECDown=-99;
  p_RelativeStatHFUp=-99;
  p_RelativeStatHFDown=-99;
  p_PileUpDataMCUp=-99;
  p_PileUpDataMCDown=-99;
  p_PileUpPtRefUp=-99;
  p_PileUpPtRefDown=-99;
  p_PileUpPtBBUp=-99;
  p_PileUpPtBBDown=-99;
  p_PileUpPtEC1Up=-99;
  p_PileUpPtEC1Down=-99;
  p_PileUpPtEC2Up=-99;
  p_PileUpPtEC2Down=-99;
  p_PileUpPtHFUp=-99;
  p_PileUpPtHFDown=-99;
  p_RelativeBalUp=-99;
  p_RelativeBalDown=-99;
  p_JERUp=-99;
  p_JERDown=-99;
  p_err_sig=-99;
  p_err_bkg=-99;
  n_perm_sig=-99;
  n_perm_bkg=-99;
  
}

DataBaseMEMResult::~DataBaseMEMResult(){}
